### ISSUE TITLE
Fruit Tree Tweaks Spanish Translation Integration

### ISSUE THREAD

**Issue by chiccenDev** [chiccenFL/StardewValleyMods#4]
Translation completed! I've translated the mod into Spanish [es.json](https://github.com/user-attachments/files/17895425/es.json). Please let me know if there are any adjustments needed.

_Originally posted by @andREAforU in https://github.com/StardewModders/mod-translations/issues/66#issuecomment-2496321395_

**Comment by chiccenFL** [comment]
Integrated ([67ac6d4](https://github.com/chiccenFL/StardewValleyMods/commit/67ac6d45efdcb516a261844435f70d74806e6ee7)). Thank you, @andREAforU ! Let me know if you'd like any further credits, I am pretty open minded and always incredibly grateful for the help!

**Comment by chiccenDev** [comment]
Integrated ([67ac6d4](https://github.com/chiccenFL/StardewValleyMods/commit/67ac6d45efdcb516a261844435f70d74806e6ee7)). Thank you, @andREAforU ! Let me know if you'd like any further credits, I am pretty open minded and always incredibly grateful for the help!
